// Browser-native PDF generation using HTML canvas and download
// This approach creates a formatted text document that can be downloaded

interface PDFData {
  totalScore: number;
  sectionScores: Array<{
    sectionNumber: number;
    titleEn: string;
    titleHi: string;
    score: number;
    status: 'alert' | 'needsWork' | 'optimal';
  }>;
  primaryProblems: string[];
  habitSuggestions: string[];
  userName: string;
}

export async function generateWellnessPDF(data: PDFData): Promise<void> {
  // Create a formatted text report
  const reportLines: string[] = [];
  
  // Header
  reportLines.push('═══════════════════════════════════════════════════════');
  reportLines.push('           THE ORGANIC EARTH');
  reportLines.push('         YOUR WELLNESS REPORT');
  reportLines.push('═══════════════════════════════════════════════════════');
  reportLines.push('');
  
  // User Info
  reportLines.push(`Name: ${data.userName}`);
  reportLines.push(`Date: ${new Date().toLocaleDateString()}`);
  reportLines.push('');
  
  // Total Score
  reportLines.push('───────────────────────────────────────────────────────');
  reportLines.push('                 TOTAL ABL SCORE');
  reportLines.push(`                  ${data.totalScore}/160`);
  reportLines.push('───────────────────────────────────────────────────────');
  reportLines.push('');
  
  // Section Breakdown
  reportLines.push('SECTION BREAKDOWN:');
  reportLines.push('');
  
  for (const section of data.sectionScores) {
    const statusLabel = section.status === 'alert' 
      ? 'Alert ⚠️' 
      : section.status === 'needsWork' 
      ? 'Needs Work ⚡' 
      : 'Good ✓';
    
    reportLines.push(`${section.titleEn}`);
    reportLines.push(`  Score: ${section.score}/40`);
    reportLines.push(`  Status: ${statusLabel}`);
    reportLines.push('');
  }
  
  // Primary Problems
  if (data.primaryProblems.length > 0) {
    reportLines.push('───────────────────────────────────────────────────────');
    reportLines.push('PRIMARY PROBLEMS:');
    reportLines.push('');
    reportLines.push(data.primaryProblems.join(', '));
    reportLines.push('');
  }
  
  // Habit Suggestions
  if (data.habitSuggestions.length > 0) {
    reportLines.push('───────────────────────────────────────────────────────');
    reportLines.push('SMALL HABIT SUGGESTIONS:');
    reportLines.push('');
    for (const suggestion of data.habitSuggestions) {
      reportLines.push(`• ${suggestion}`);
    }
    reportLines.push('');
  }
  
  // Footer
  reportLines.push('═══════════════════════════════════════════════════════');
  reportLines.push('Generated by The Organic Earth - ABL Pulse Assessment');
  reportLines.push(`${new Date().toLocaleString()}`);
  reportLines.push('═══════════════════════════════════════════════════════');
  
  // Create downloadable text file
  const reportText = reportLines.join('\n');
  const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  // Create download link
  const link = document.createElement('a');
  link.href = url;
  const fileName = `ABL-Wellness-Report-${data.userName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
  link.download = fileName;
  
  // Trigger download
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
