/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface SolutionTip {
    medicalFitForHeartProblems: boolean;
    medicalFitForThyroid: boolean;
    medicalFitForHighBMI: boolean;
    text: string;
    section: SectionId;
    costLevel: Variant_low_high_medium;
    timeCommitment: Variant_long_short_medium;
    medicalFitForAlcoholUse: boolean;
    medicalFitForAnemia: boolean;
    severity: Variant_low_high_medium;
    medicalFitForKidney: boolean;
    medicalFitForPregnancy: boolean;
    medicalFitForBloodPressure: boolean;
    medicalRisk: Variant_low_high_none;
    medicalFitForCholesterol: boolean;
    suitability: Variant_all_elderly_pregnant_youth;
    medicalFitForSugar: boolean;
}
export interface SectionScores {
    diet: bigint;
    exercise: bigint;
    sleep: bigint;
    hydration: bigint;
}
export interface MedicalHistory {
    hasProblemsWithPregnancy: boolean;
    hasProblemsWithAlcoholUse: boolean;
    hasProblemsWithCholesterol: boolean;
    hasProblemsWithAnemia: boolean;
    hasProblemsWithBloodPressure: boolean;
    hasProblemsWithKidney: boolean;
    hasProblemsWithSugar: boolean;
    hasProblemsWithHeartProblems: boolean;
    hasProblemsWithThyroid: boolean;
    hasProblemsWithHighBMI: boolean;
}
export interface CompleteWellnessReport {
    recommendations: Array<SolutionTip>;
    scores: SectionScores;
    problems: Array<string>;
    timestamp: Time;
    healthProfile: {
        answers: UserAnswers;
        medicalHistory: MedicalHistory;
    };
}
export interface UserProfile {
    name: string;
}
export interface UserAnswers {
    diet: Array<bigint>;
    exercise: Array<bigint>;
    sleep: Array<bigint>;
    hydration: Array<bigint>;
}
export enum SectionId {
    diet = "diet",
    exercise = "exercise",
    sleep = "sleep",
    hydration = "hydration"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_all_elderly_pregnant_youth {
    all = "all",
    elderly = "elderly",
    pregnant = "pregnant",
    youth = "youth"
}
export enum Variant_long_short_medium {
    long_ = "long",
    short_ = "short",
    medium = "medium"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Variant_low_high_none {
    low = "low",
    high = "high",
    none = "none"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllSections(): Promise<Array<SectionId>>;
    getAllWellnessReports(): Promise<Array<[bigint, CompleteWellnessReport]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSectionScoringDetails(): Promise<{
        questionPoints: Array<[SectionId, Array<bigint>]>;
        scoringReference: Array<[bigint, string]>;
        sectionEndQuestion: Array<[SectionId, bigint]>;
        sectionStartQuestion: Array<[SectionId, bigint]>;
    }>;
    getTestData(): Promise<[SectionScores, SectionScores, SectionScores, MedicalHistory, MedicalHistory, MedicalHistory]>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWellnessReportById(id: bigint): Promise<CompleteWellnessReport | null>;
    isAdminUser(_email: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveWellnessReport(report: CompleteWellnessReport): Promise<bigint>;
    validateMedicalHistory(medicalHistory: MedicalHistory): Promise<MedicalHistory>;
}
import type { CompleteWellnessReport as _CompleteWellnessReport, MedicalHistory as _MedicalHistory, SectionId as _SectionId, SectionScores as _SectionScores, SolutionTip as _SolutionTip, Time as _Time, UserAnswers as _UserAnswers, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllSections(): Promise<Array<SectionId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSections();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSections();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWellnessReports(): Promise<Array<[bigint, CompleteWellnessReport]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWellnessReports();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWellnessReports();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSectionScoringDetails(): Promise<{
        questionPoints: Array<[SectionId, Array<bigint>]>;
        scoringReference: Array<[bigint, string]>;
        sectionEndQuestion: Array<[SectionId, bigint]>;
        sectionStartQuestion: Array<[SectionId, bigint]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionScoringDetails();
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionScoringDetails();
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestData(): Promise<[SectionScores, SectionScores, SectionScores, MedicalHistory, MedicalHistory, MedicalHistory]> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestData();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4],
                    result[5]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestData();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4],
                result[5]
            ];
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWellnessReportById(arg0: bigint): Promise<CompleteWellnessReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWellnessReportById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWellnessReportById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUser(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveWellnessReport(arg0: CompleteWellnessReport): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWellnessReport(to_candid_CompleteWellnessReport_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWellnessReport(to_candid_CompleteWellnessReport_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateMedicalHistory(arg0: MedicalHistory): Promise<MedicalHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.validateMedicalHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateMedicalHistory(arg0);
            return result;
        }
    }
}
function from_candid_CompleteWellnessReport_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompleteWellnessReport): CompleteWellnessReport {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SectionId_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionId): SectionId {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SolutionTip_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolutionTip): SolutionTip {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompleteWellnessReport]): CompleteWellnessReport | null {
    return value.length === 0 ? null : from_candid_CompleteWellnessReport_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medicalFitForHeartProblems: boolean;
    medicalFitForThyroid: boolean;
    medicalFitForHighBMI: boolean;
    text: string;
    section: _SectionId;
    costLevel: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    timeCommitment: {
        long: null;
    } | {
        short: null;
    } | {
        medium: null;
    };
    medicalFitForAlcoholUse: boolean;
    medicalFitForAnemia: boolean;
    severity: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    medicalFitForKidney: boolean;
    medicalFitForPregnancy: boolean;
    medicalFitForBloodPressure: boolean;
    medicalRisk: {
        low: null;
    } | {
        high: null;
    } | {
        none: null;
    };
    medicalFitForCholesterol: boolean;
    suitability: {
        all: null;
    } | {
        elderly: null;
    } | {
        pregnant: null;
    } | {
        youth: null;
    };
    medicalFitForSugar: boolean;
}): {
    medicalFitForHeartProblems: boolean;
    medicalFitForThyroid: boolean;
    medicalFitForHighBMI: boolean;
    text: string;
    section: SectionId;
    costLevel: Variant_low_high_medium;
    timeCommitment: Variant_long_short_medium;
    medicalFitForAlcoholUse: boolean;
    medicalFitForAnemia: boolean;
    severity: Variant_low_high_medium;
    medicalFitForKidney: boolean;
    medicalFitForPregnancy: boolean;
    medicalFitForBloodPressure: boolean;
    medicalRisk: Variant_low_high_none;
    medicalFitForCholesterol: boolean;
    suitability: Variant_all_elderly_pregnant_youth;
    medicalFitForSugar: boolean;
} {
    return {
        medicalFitForHeartProblems: value.medicalFitForHeartProblems,
        medicalFitForThyroid: value.medicalFitForThyroid,
        medicalFitForHighBMI: value.medicalFitForHighBMI,
        text: value.text,
        section: from_candid_SectionId_n4(_uploadFile, _downloadFile, value.section),
        costLevel: from_candid_variant_n13(_uploadFile, _downloadFile, value.costLevel),
        timeCommitment: from_candid_variant_n14(_uploadFile, _downloadFile, value.timeCommitment),
        medicalFitForAlcoholUse: value.medicalFitForAlcoholUse,
        medicalFitForAnemia: value.medicalFitForAnemia,
        severity: from_candid_variant_n13(_uploadFile, _downloadFile, value.severity),
        medicalFitForKidney: value.medicalFitForKidney,
        medicalFitForPregnancy: value.medicalFitForPregnancy,
        medicalFitForBloodPressure: value.medicalFitForBloodPressure,
        medicalRisk: from_candid_variant_n15(_uploadFile, _downloadFile, value.medicalRisk),
        medicalFitForCholesterol: value.medicalFitForCholesterol,
        suitability: from_candid_variant_n16(_uploadFile, _downloadFile, value.suitability),
        medicalFitForSugar: value.medicalFitForSugar
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questionPoints: Array<[_SectionId, Array<bigint>]>;
    scoringReference: Array<[bigint, string]>;
    sectionEndQuestion: Array<[_SectionId, bigint]>;
    sectionStartQuestion: Array<[_SectionId, bigint]>;
}): {
    questionPoints: Array<[SectionId, Array<bigint>]>;
    scoringReference: Array<[bigint, string]>;
    sectionEndQuestion: Array<[SectionId, bigint]>;
    sectionStartQuestion: Array<[SectionId, bigint]>;
} {
    return {
        questionPoints: from_candid_vec_n21(_uploadFile, _downloadFile, value.questionPoints),
        scoringReference: value.scoringReference,
        sectionEndQuestion: from_candid_vec_n23(_uploadFile, _downloadFile, value.sectionEndQuestion),
        sectionStartQuestion: from_candid_vec_n23(_uploadFile, _downloadFile, value.sectionStartQuestion)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: Array<_SolutionTip>;
    scores: _SectionScores;
    problems: Array<string>;
    timestamp: _Time;
    healthProfile: {
        answers: _UserAnswers;
        medicalHistory: _MedicalHistory;
    };
}): {
    recommendations: Array<SolutionTip>;
    scores: SectionScores;
    problems: Array<string>;
    timestamp: Time;
    healthProfile: {
        answers: UserAnswers;
        medicalHistory: MedicalHistory;
    };
} {
    return {
        recommendations: from_candid_vec_n10(_uploadFile, _downloadFile, value.recommendations),
        scores: value.scores,
        problems: value.problems,
        timestamp: value.timestamp,
        healthProfile: value.healthProfile
    };
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_SectionId, Array<bigint>]): [SectionId, Array<bigint>] {
    return [
        from_candid_SectionId_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_SectionId, bigint]): [SectionId, bigint] {
    return [
        from_candid_SectionId_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _CompleteWellnessReport]): [bigint, CompleteWellnessReport] {
    return [
        value[0],
        from_candid_CompleteWellnessReport_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
} | {
    medium: null;
}): Variant_long_short_medium {
    return "long" in value ? Variant_long_short_medium.long : "short" in value ? Variant_long_short_medium.short : "medium" in value ? Variant_long_short_medium.medium : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    none: null;
}): Variant_low_high_none {
    return "low" in value ? Variant_low_high_none.low : "high" in value ? Variant_low_high_none.high : "none" in value ? Variant_low_high_none.none : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    elderly: null;
} | {
    pregnant: null;
} | {
    youth: null;
}): Variant_all_elderly_pregnant_youth {
    return "all" in value ? Variant_all_elderly_pregnant_youth.all : "elderly" in value ? Variant_all_elderly_pregnant_youth.elderly : "pregnant" in value ? Variant_all_elderly_pregnant_youth.pregnant : "youth" in value ? Variant_all_elderly_pregnant_youth.youth : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diet: null;
} | {
    exercise: null;
} | {
    sleep: null;
} | {
    hydration: null;
}): SectionId {
    return "diet" in value ? SectionId.diet : "exercise" in value ? SectionId.exercise : "sleep" in value ? SectionId.sleep : "hydration" in value ? SectionId.hydration : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SolutionTip>): Array<SolutionTip> {
    return value.map((x)=>from_candid_SolutionTip_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_SectionId, Array<bigint>]>): Array<[SectionId, Array<bigint>]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_SectionId, bigint]>): Array<[SectionId, bigint]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SectionId>): Array<SectionId> {
    return value.map((x)=>from_candid_SectionId_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _CompleteWellnessReport]>): Array<[bigint, CompleteWellnessReport]> {
    return value.map((x)=>from_candid_tuple_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CompleteWellnessReport_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompleteWellnessReport): _CompleteWellnessReport {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_SectionId_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionId): _SectionId {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_SolutionTip_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SolutionTip): _SolutionTip {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: Array<SolutionTip>;
    scores: SectionScores;
    problems: Array<string>;
    timestamp: Time;
    healthProfile: {
        answers: UserAnswers;
        medicalHistory: MedicalHistory;
    };
}): {
    recommendations: Array<_SolutionTip>;
    scores: _SectionScores;
    problems: Array<string>;
    timestamp: _Time;
    healthProfile: {
        answers: _UserAnswers;
        medicalHistory: _MedicalHistory;
    };
} {
    return {
        recommendations: to_candid_vec_n28(_uploadFile, _downloadFile, value.recommendations),
        scores: value.scores,
        problems: value.problems,
        timestamp: value.timestamp,
        healthProfile: value.healthProfile
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medicalFitForHeartProblems: boolean;
    medicalFitForThyroid: boolean;
    medicalFitForHighBMI: boolean;
    text: string;
    section: SectionId;
    costLevel: Variant_low_high_medium;
    timeCommitment: Variant_long_short_medium;
    medicalFitForAlcoholUse: boolean;
    medicalFitForAnemia: boolean;
    severity: Variant_low_high_medium;
    medicalFitForKidney: boolean;
    medicalFitForPregnancy: boolean;
    medicalFitForBloodPressure: boolean;
    medicalRisk: Variant_low_high_none;
    medicalFitForCholesterol: boolean;
    suitability: Variant_all_elderly_pregnant_youth;
    medicalFitForSugar: boolean;
}): {
    medicalFitForHeartProblems: boolean;
    medicalFitForThyroid: boolean;
    medicalFitForHighBMI: boolean;
    text: string;
    section: _SectionId;
    costLevel: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    timeCommitment: {
        long: null;
    } | {
        short: null;
    } | {
        medium: null;
    };
    medicalFitForAlcoholUse: boolean;
    medicalFitForAnemia: boolean;
    severity: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    medicalFitForKidney: boolean;
    medicalFitForPregnancy: boolean;
    medicalFitForBloodPressure: boolean;
    medicalRisk: {
        low: null;
    } | {
        high: null;
    } | {
        none: null;
    };
    medicalFitForCholesterol: boolean;
    suitability: {
        all: null;
    } | {
        elderly: null;
    } | {
        pregnant: null;
    } | {
        youth: null;
    };
    medicalFitForSugar: boolean;
} {
    return {
        medicalFitForHeartProblems: value.medicalFitForHeartProblems,
        medicalFitForThyroid: value.medicalFitForThyroid,
        medicalFitForHighBMI: value.medicalFitForHighBMI,
        text: value.text,
        section: to_candid_SectionId_n31(_uploadFile, _downloadFile, value.section),
        costLevel: to_candid_variant_n33(_uploadFile, _downloadFile, value.costLevel),
        timeCommitment: to_candid_variant_n34(_uploadFile, _downloadFile, value.timeCommitment),
        medicalFitForAlcoholUse: value.medicalFitForAlcoholUse,
        medicalFitForAnemia: value.medicalFitForAnemia,
        severity: to_candid_variant_n33(_uploadFile, _downloadFile, value.severity),
        medicalFitForKidney: value.medicalFitForKidney,
        medicalFitForPregnancy: value.medicalFitForPregnancy,
        medicalFitForBloodPressure: value.medicalFitForBloodPressure,
        medicalRisk: to_candid_variant_n35(_uploadFile, _downloadFile, value.medicalRisk),
        medicalFitForCholesterol: value.medicalFitForCholesterol,
        suitability: to_candid_variant_n36(_uploadFile, _downloadFile, value.suitability),
        medicalFitForSugar: value.medicalFitForSugar
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionId): {
    diet: null;
} | {
    exercise: null;
} | {
    sleep: null;
} | {
    hydration: null;
} {
    return value == SectionId.diet ? {
        diet: null
    } : value == SectionId.exercise ? {
        exercise: null
    } : value == SectionId.sleep ? {
        sleep: null
    } : value == SectionId.hydration ? {
        hydration: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_long_short_medium): {
    long: null;
} | {
    short: null;
} | {
    medium: null;
} {
    return value == Variant_long_short_medium.long ? {
        long_: null
    } : value == Variant_long_short_medium.short ? {
        short_: null
    } : value == Variant_long_short_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_none): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} {
    return value == Variant_low_high_none.low ? {
        low: null
    } : value == Variant_low_high_none.high ? {
        high: null
    } : value == Variant_low_high_none.none ? {
        none: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_all_elderly_pregnant_youth): {
    all: null;
} | {
    elderly: null;
} | {
    pregnant: null;
} | {
    youth: null;
} {
    return value == Variant_all_elderly_pregnant_youth.all ? {
        all: null
    } : value == Variant_all_elderly_pregnant_youth.elderly ? {
        elderly: null
    } : value == Variant_all_elderly_pregnant_youth.pregnant ? {
        pregnant: null
    } : value == Variant_all_elderly_pregnant_youth.youth ? {
        youth: null
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SolutionTip>): Array<_SolutionTip> {
    return value.map((x)=>to_candid_SolutionTip_n29(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
